API v3.1 additions
onfido/onfido-openapi-spec pull request #11
Opened 2021-03-03 15:59 UTC by Phoebe-B

- Add `webhook_ids` 
- Add download check PDF endpoint

2021-03-03 16:03 UTC, superdevx64 approved these changes

2021-03-08 15:17 UTC, ciaran16 requested changes
`privacy_notices_read_consent_given` doesn't need the `writeOnly: true` in v3.1

2021-03-08 15:17 UTC, ciaran16 commented on paths/checks.yaml
> +    post:
This will be a get request like the other download endpoints

2021-03-08 15:47 UTC, ciaran16 approved these changes
Looks good 👍 I assume we're holding off on merging this for a bit?

2021-03-08 15:50 UTC, ciaran16 reviewed
Actually we need to update a few URLs in `openapi.yaml` to point to `v3.1` as well

2021-04-12 11:25 UTC, merged